version: '2'
services:
  app:
    # Containers
    build: .
    image: snake-multiplayer
    container_name: snake-multiplayer

    # Networking
    network_mode: "bridge"
    ports:
      - "127.0.0.1:8000:8000"
